name: credit-card-analysis
services:
  - name: credit-card-analysis
    github:
      repo: philippe-pcs/credit-card-analysis
      branch: master
      deploy_on_push: true
    build_command: npm run build
    source_dir: dist
    http_port: 8080
    envs:
      - key: VITE_GOOGLE_GENERATIVE_AI_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${VITE_GOOGLE_GENERATIVE_AI_KEY}
